using System;
using System.Collections.Generic;

namespace RLHub2.Helpers
{
    public enum AppLanguage { Polish, English }

    // App-wide language. Pages read strings via T(key) and rebuild on LanguageChanged.
    public static class Localization
    {
        public static AppLanguage Language { get; private set; } = AppLanguage.Polish;

        public static event Action? LanguageChanged;

        public static bool IsPolish => Language == AppLanguage.Polish;

        // Set without firing the event (startup).
        public static void Initialize(AppLanguage lang) => Language = lang;

        public static void SetLanguage(AppLanguage lang)
        {
            if (Language == lang) return;
            Language = lang;
            LanguageChanged?.Invoke();
        }

        public static string T(string key)
        {
            var map = IsPolish ? Pl : En;
            var value = map.TryGetValue(key, out var v) ? v : key;
            return value.ToUpperInvariant(); // UI uses all-caps everywhere
        }

        private static readonly Dictionary<string, string> En = new()
        {
            ["nav_home"] = "Home",
            ["nav_mmr"] = "MMR Tracker",
            ["nav_news"] = "News",
            ["nav_profile"] = "Profile",
            ["nav_tournaments"] = "Tournaments",
            ["nav_seasons"] = "Seasons",
            ["nav_settings"] = "Settings",
            ["nav_goals"] = "Goals",
            ["nav_sec_main"] = "MAIN",
            ["nav_sec_social"] = "COMMUNITY",
            ["nav_sec_extra"] = "EXTRAS",

            ["goals_title"] = "GOALS",
            ["goals_add_ph"] = "New goal, e.g. Champion 1",
            ["goals_add"] = "ADD",
            ["goals_delete"] = "DELETE",
            ["goals_col_goal"] = "GOAL",
            ["goals_done_word"] = "done",
            ["goals_empty"] = "No goals yet — add one above",

            ["nav_garage"] = "Garage",
            ["garage_title"] = "GARAGE",
            ["garage_presets"] = "CAR PRESETS",
            ["garage_ach"] = "ACHIEVEMENTS",
            ["garage_preset_ph"] = "Preset name",
            ["garage_ach_ph"] = "New achievement, e.g. 10 win streak",
            ["garage_add"] = "ADD",
            ["garage_delete"] = "DELETE",
            ["garage_export"] = "⭳ EXPORT",
            ["garage_col_name"] = "NAME",
            ["garage_col_body"] = "BODY",
            ["garage_col_ach"] = "ACHIEVEMENT",
            ["garage_exported"] = "Presets exported",

            ["nav_road"] = "Road to SSL",
            ["road_title"] = "ROAD TO SSL",
            ["road_current"] = "Current",
            ["road_tonext"] = "To next",
            ["road_pace"] = "Pace",
            ["road_eta"] = "ETA",
            ["road_wk"] = "wk",
            ["road_empty"] = "Add MMR entries to see your road",
            ["road_maxed"] = "You reached the top — SSL!",

            ["nav_session"] = "Session",
            ["session_title"] = "SESSION TRACKER",
            ["session_status_on"] = "Connected — playing live",
            ["session_status_off"] = "Waiting for Rocket League",
            ["session_record"] = "W – L",
            ["session_winrate"] = "WIN RATE",
            ["session_streak"] = "STREAK",
            ["session_matches"] = "MATCHES",
            ["session_avg_goals"] = "GOALS/GAME",
            ["session_avg_saves"] = "SAVES/GAME",
            ["session_avg_assists"] = "ASSISTS/GAME",
            ["session_recent"] = "RECENT MATCHES",
            ["session_reset"] = "RESET",
            ["session_win"] = "WIN",
            ["session_loss"] = "LOSS",
            ["session_empty_short"] = "No matches this session yet",

            ["nav_records"] = "Records",
            ["records_title"] = "RECORDS",
            ["records_history"] = "SEASON HISTORY",
            ["records_mmr"] = "HIGHEST MMR",
            ["records_streak"] = "LONGEST WIN STREAK",
            ["records_goals"] = "MOST GOALS (1 MATCH)",
            ["records_gain"] = "BIGGEST MMR GAIN / DAY",
            ["records_session"] = "BEST SESSION",
            ["records_games"] = "games",
            ["records_in_progress"] = "live",
            ["records_history_empty"] = "No season archived yet — Season 23 is in progress",

            ["nav_coach"] = "AI Coach",
            ["coach_title"] = "AI COACH",
            ["coach_gpm"] = "GOALS/GAME",
            ["coach_spm"] = "SAVES/GAME",
            ["coach_apm"] = "ASSISTS/GAME",
            ["coach_win"] = "WIN RATE",
            ["coach_advice"] = "ADVICE",
            ["coach_no_nick"] = "Set a player nick in Settings to get coached.",
            ["coach_loading"] = "Analyzing your stats…",
            ["coach_low_saves"] = "❌ Too few saves — train defense and rotations.",
            ["coach_low_goals"] = "❌ Too few goals — work on shooting and positioning.",
            ["coach_low_assists"] = "❌ Few assists — play more as a team.",
            ["coach_aggressive"] = "❌ Very attack-heavy — you score but barely defend.",
            ["coach_good"] = "✅ Solid, balanced stats — keep it up!",

            ["nav_friends"] = "Friends",
            ["friends_title"] = "FRIENDS",
            ["friends_add_ph"] = "Friend nick (Epic / Steam)",
            ["friends_add"] = "ADD",
            ["friends_delete"] = "DELETE",
            ["friends_refresh"] = "↻ REFRESH",
            ["friends_col_nick"] = "PLAYER",
            ["friends_col_mmr"] = "MMR (2v2)",
            ["friends_empty"] = "Add friend nicks to compare MMR",
            ["friends_loading"] = "Fetching friends…",

            ["home_banner_sub"] = "Your Rocket League command center",
            ["home_open_news"] = "OPEN NEWS",
            ["home_latest_news"] = "LATEST NEWS",
            ["home_tile_season"] = "SEASON",
            ["home_tile_servers"] = "SERVER STATUS",
            ["home_tile_season_end"] = "SEASON ENDS",
            ["home_tile_challenges"] = "CHALLENGES RESET",
            ["home_tile_tournaments"] = "TOURNAMENTS RESET",
            ["home_player"] = "PLAYER",
            ["home_rank2v2"] = "RANK (2V2)",
            ["home_week"] = "MMR THIS WEEK",
            ["home_road"] = "ROAD TO",
            ["home_no_data"] = "Add MMR entries in the MMR Tracker",
            ["home_maxed"] = "Top rank reached",

            ["news_title"] = "NEWS",
            ["news_all"] = "ALL",
            ["news_general"] = "GENERAL",
            ["news_esports"] = "ESPORTS",
            ["news_updates"] = "UPDATES",

            ["mmr_title"] = "MMR TRACKER",
            ["mmr_choose"] = "Choose a playlist",
            ["mmr_back"] = "← BACK",
            ["mmr_week"] = "WEEK",
            ["mmr_month"] = "MONTH",
            ["mmr_season"] = "SEASON",
            ["mmr_all"] = "ALL",
            ["mmr_add_title"] = "ADD ENTRY",
            ["mmr_edit_title"] = "EDIT ENTRY",
            ["mmr_edit_btn"] = "EDIT SELECTED",
            ["mmr_delete"] = "DELETE",
            ["mmr_undo"] = "↶ UNDO",
            ["mmr_cancel"] = "CANCEL EDIT",
            ["mmr_hint_add"] = "↵  Press Enter to add",
            ["mmr_hint_save"] = "↵  Press Enter to save",
            ["mmr_col_date"] = "DATE",
            ["mmr_col_mmr"] = "MMR",
            ["mmr_empty"] = "No data yet",
            ["mmr_empty_sub"] = "Add your first MMR entry below",
            ["mmr_peak"] = "Peak",
            ["mmr_avg"] = "Avg",
            ["mmr_change"] = "Change",
            ["mmr_peak_all"] = "All-time peak",
            ["mmr_week"] = "This week",
            ["mmr_next"] = "Next",
            ["mmr_next_none"] = "grind on",
            ["mmr_export"] = "⭳ EXPORT",
            ["mmr_import"] = "⭱ IMPORT",
            ["mmr_folder"] = "📁 FOLDER",
            ["mmr_exported"] = "Exported",
            ["mmr_imported"] = "Imported",
            ["mmr_fetch"] = "⭳ FETCH MMR",
            ["mmr_fetched"] = "MMR fetched from tracker.gg",
            ["mmr_fetch_nonick"] = "Set a player nick in Settings first",
            ["mmr_fetch_fail"] = "Could not fetch MMR (check key / nick)",
            ["settings_nick"] = "PLAYER NICK",
            ["settings_nick_hint"] = "Used to auto-fetch MMR and the profile",
            ["mmr_confirm_delete"] = "Delete this MMR entry?",
            ["mmr_invalid"] = "Enter a valid MMR number.",

            ["settings_title"] = "SETTINGS",
            ["settings_language"] = "LANGUAGE",
            ["settings_language_hint"] = "Language of the whole application",
            ["settings_key"] = "TRACKER.GG API KEY",
            ["settings_key_hint"] = "Get a free key at tracker.gg/developers, then paste it here for real profiles",
            ["settings_save"] = "SAVE",
            ["settings_saved"] = "Saved",
            ["settings_theme"] = "THEME",
            ["settings_theme_hint"] = "Light or dark appearance",
            ["theme_dark"] = "Dark",
            ["theme_light"] = "Light",
            ["settings_accent"] = "ACCENT COLOR",
            ["settings_accent_hint"] = "Pick the highlight color",

            ["page_profile"] = "PROFILE",
            ["page_tournaments"] = "TOURNAMENTS",
            ["page_seasons"] = "SEASONS",

            ["profile_search_ph"] = "Enter player nickname",
            ["profile_search_btn"] = "SEARCH",
            ["profile_prompt"] = "Search for a player to see their stats",
            ["profile_ranks"] = "RANKS",
            ["profile_stats"] = "STATISTICS",
            ["profile_seasons"] = "RECENT MATCHES",
            ["profile_wins"] = "WINS",
            ["profile_matches"] = "MATCHES",
            ["profile_goals"] = "GOALS",
            ["profile_assists"] = "ASSISTS",
            ["profile_col_season"] = "DATE",
            ["profile_col_rank"] = "RANK",
            ["profile_col_mmr"] = "MMR",
            ["profile_loading"] = "Loading…",
            ["profile_error"] = "Could not load this player. Check the nickname (the player must have a public Rocket League profile).",
            ["profile_no_key"] = "Set your tracker.gg API key in Settings to load real profiles.",

            ["tour_all"] = "ALL",
            ["tour_rlcs"] = "RLCS",
            ["tour_major"] = "MAJORS",
            ["tour_regional"] = "REGIONAL",
            ["tour_empty"] = "No tournaments found",
            ["tour_loading"] = "Loading tournaments…",

            ["season_changes"] = "CHANGES",
            ["season_new"] = "NEW",
            ["season_rewards"] = "REWARDS",

            ["refresh"] = "↻ REFRESH",
            ["news_loading"] = "Loading news…",
            ["news_empty"] = "No news found",
        };

        private static readonly Dictionary<string, string> Pl = new()
        {
            ["nav_home"] = "Start",
            ["nav_mmr"] = "Śledzenie MMR",
            ["nav_news"] = "Aktualności",
            ["nav_profile"] = "Profil",
            ["nav_tournaments"] = "Turnieje",
            ["nav_seasons"] = "Sezony",
            ["nav_settings"] = "Ustawienia",
            ["nav_goals"] = "Cele",
            ["nav_sec_main"] = "GŁÓWNE",
            ["nav_sec_social"] = "SPOŁECZNOŚĆ",
            ["nav_sec_extra"] = "DODATKI",

            ["goals_title"] = "CELE",
            ["goals_add_ph"] = "Nowy cel, np. Champion 1",
            ["goals_add"] = "DODAJ",
            ["goals_delete"] = "USUŃ",
            ["goals_col_goal"] = "CEL",
            ["goals_done_word"] = "ukończone",
            ["goals_empty"] = "Brak celów — dodaj powyżej",

            ["nav_garage"] = "Garaż",
            ["garage_title"] = "GARAŻ",
            ["garage_presets"] = "PRESETY AUT",
            ["garage_ach"] = "OSIĄGNIĘCIA",
            ["garage_preset_ph"] = "Nazwa presetu",
            ["garage_ach_ph"] = "Nowe osiągnięcie, np. 10 win streak",
            ["garage_add"] = "DODAJ",
            ["garage_delete"] = "USUŃ",
            ["garage_export"] = "⭳ EKSPORT",
            ["garage_col_name"] = "NAZWA",
            ["garage_col_body"] = "NADWOZIE",
            ["garage_col_ach"] = "OSIĄGNIĘCIE",
            ["garage_exported"] = "Presety wyeksportowane",

            ["nav_road"] = "Droga do SSL",
            ["road_title"] = "DROGA DO SSL",
            ["road_current"] = "Aktualne",
            ["road_tonext"] = "Do kolejnej",
            ["road_pace"] = "Tempo",
            ["road_eta"] = "Szac.",
            ["road_wk"] = "tyg",
            ["road_empty"] = "Dodaj wpisy MMR, aby zobaczyć drogę",
            ["road_maxed"] = "Osiągnąłeś szczyt — SSL!",

            ["nav_session"] = "Sesja",
            ["session_title"] = "TRACKER SESJI",
            ["session_status_on"] = "Połączono — grasz na żywo",
            ["session_status_off"] = "Czekam na Rocket League",
            ["session_record"] = "W – P",
            ["session_winrate"] = "WYGRANE",
            ["session_streak"] = "SERIA",
            ["session_matches"] = "MECZE",
            ["session_avg_goals"] = "GOLE/MECZ",
            ["session_avg_saves"] = "OBRONY/MECZ",
            ["session_avg_assists"] = "ASYSTY/MECZ",
            ["session_recent"] = "OSTATNIE MECZE",
            ["session_reset"] = "RESET",
            ["session_win"] = "WYGRANA",
            ["session_loss"] = "PRZEGRANA",
            ["session_empty_short"] = "Brak meczów w tej sesji",

            ["nav_records"] = "Rekordy",
            ["records_title"] = "REKORDY",
            ["records_history"] = "HISTORIA SEZONÓW",
            ["records_mmr"] = "NAJWYŻSZE MMR",
            ["records_streak"] = "NAJDŁUŻSZA SERIA W",
            ["records_goals"] = "NAJWIĘCEJ GOLI (1 MECZ)",
            ["records_gain"] = "NAJWIĘKSZY SKOK MMR / DZIEŃ",
            ["records_session"] = "NAJLEPSZA SESJA",
            ["records_games"] = "meczów",
            ["records_in_progress"] = "w toku",
            ["records_history_empty"] = "Brak zarchiwizowanych sezonów — Season 23 trwa",

            ["nav_coach"] = "AI Coach",
            ["coach_title"] = "AI COACH",
            ["coach_gpm"] = "GOLE/MECZ",
            ["coach_spm"] = "OBRONY/MECZ",
            ["coach_apm"] = "ASYSTY/MECZ",
            ["coach_win"] = "WINRATE",
            ["coach_advice"] = "WSKAZÓWKI",
            ["coach_no_nick"] = "Ustaw nick gracza w Ustawieniach, aby dostać wskazówki.",
            ["coach_loading"] = "Analizuję Twoje statystyki…",
            ["coach_low_saves"] = "❌ Za mało obron — trenuj obronę i rotacje.",
            ["coach_low_goals"] = "❌ Za mało goli — popracuj nad strzałami i pozycją.",
            ["coach_low_assists"] = "❌ Mało asyst — graj bardziej zespołowo.",
            ["coach_aggressive"] = "❌ Bardzo ofensywnie — strzelasz, ale prawie nie bronisz.",
            ["coach_good"] = "✅ Solidne, zrównoważone staty — tak trzymaj!",

            ["nav_friends"] = "Znajomi",
            ["friends_title"] = "ZNAJOMI",
            ["friends_add_ph"] = "Nick znajomego (Epic / Steam)",
            ["friends_add"] = "DODAJ",
            ["friends_delete"] = "USUŃ",
            ["friends_refresh"] = "↻ ODŚWIEŻ",
            ["friends_col_nick"] = "GRACZ",
            ["friends_col_mmr"] = "MMR (2v2)",
            ["friends_empty"] = "Dodaj nicki znajomych, aby porównać MMR",
            ["friends_loading"] = "Pobieram znajomych…",

            ["home_banner_sub"] = "Twoje centrum dowodzenia Rocket League",
            ["home_open_news"] = "OTWÓRZ NEWSY",
            ["home_latest_news"] = "NAJNOWSZE",
            ["home_tile_season"] = "SEZON",
            ["home_tile_servers"] = "STATUS SERWERÓW",
            ["home_tile_season_end"] = "KONIEC SEZONU",
            ["home_tile_challenges"] = "RESET WYZWAŃ",
            ["home_tile_tournaments"] = "RESET TURNIEJÓW",
            ["home_player"] = "GRACZ",
            ["home_rank2v2"] = "RANGA (2V2)",
            ["home_week"] = "MMR W TYM TYGODNIU",
            ["home_road"] = "DROGA DO",
            ["home_no_data"] = "Dodaj wpisy w MMR Trackerze",
            ["home_maxed"] = "Najwyższa ranga",

            ["news_title"] = "AKTUALNOŚCI",
            ["news_all"] = "WSZYSTKIE",
            ["news_general"] = "OGÓLNE",
            ["news_esports"] = "ESPORT",
            ["news_updates"] = "AKTUALIZACJE",

            ["mmr_title"] = "ŚLEDZENIE MMR",
            ["mmr_choose"] = "Wybierz tryb gry",
            ["mmr_back"] = "← WSTECZ",
            ["mmr_week"] = "TYDZIEŃ",
            ["mmr_month"] = "MIESIĄC",
            ["mmr_season"] = "SEZON",
            ["mmr_all"] = "WSZYSTKO",
            ["mmr_add_title"] = "DODAJ WPIS",
            ["mmr_edit_title"] = "EDYTUJ WPIS",
            ["mmr_edit_btn"] = "EDYTUJ ZAZNACZONY",
            ["mmr_delete"] = "USUŃ",
            ["mmr_undo"] = "↶ COFNIJ",
            ["mmr_cancel"] = "ANULUJ EDYCJĘ",
            ["mmr_hint_add"] = "↵  Naciśnij Enter, aby dodać",
            ["mmr_hint_save"] = "↵  Naciśnij Enter, aby zapisać",
            ["mmr_col_date"] = "DATA",
            ["mmr_col_mmr"] = "MMR",
            ["mmr_empty"] = "Brak danych",
            ["mmr_empty_sub"] = "Dodaj swój pierwszy wpis MMR poniżej",
            ["mmr_peak"] = "Szczyt",
            ["mmr_avg"] = "Średnia",
            ["mmr_change"] = "Zmiana",
            ["mmr_peak_all"] = "Rekord",
            ["mmr_week"] = "Ten tydzień",
            ["mmr_next"] = "Kolejna ranga",
            ["mmr_next_none"] = "graj dalej",
            ["mmr_export"] = "⭳ EKSPORT",
            ["mmr_import"] = "⭱ IMPORT",
            ["mmr_folder"] = "📁 FOLDER",
            ["mmr_exported"] = "Wyeksportowano",
            ["mmr_imported"] = "Zaimportowano",
            ["mmr_fetch"] = "⭳ POBIERZ MMR",
            ["mmr_fetched"] = "Pobrano MMR z tracker.gg",
            ["mmr_fetch_nonick"] = "Najpierw ustaw nick gracza w Ustawieniach",
            ["mmr_fetch_fail"] = "Nie udało się pobrać MMR (sprawdź klucz / nick)",
            ["settings_nick"] = "NICK GRACZA",
            ["settings_nick_hint"] = "Do auto-pobierania MMR i profilu",
            ["mmr_confirm_delete"] = "Usunąć ten wpis MMR?",
            ["mmr_invalid"] = "Wpisz poprawną liczbę MMR.",

            ["settings_title"] = "USTAWIENIA",
            ["settings_language"] = "JĘZYK",
            ["settings_language_hint"] = "Język całej aplikacji",
            ["settings_key"] = "KLUCZ API TRACKER.GG",
            ["settings_key_hint"] = "Darmowy klucz zdobędziesz na tracker.gg/developers — wklej go tu, by mieć prawdziwe profile",
            ["settings_save"] = "ZAPISZ",
            ["settings_saved"] = "Zapisano",
            ["settings_theme"] = "MOTYW",
            ["settings_theme_hint"] = "Wygląd jasny lub ciemny",
            ["theme_dark"] = "Ciemny",
            ["theme_light"] = "Jasny",
            ["settings_accent"] = "KOLOR AKCENTU",
            ["settings_accent_hint"] = "Wybierz kolor wyróżnień",

            ["page_profile"] = "PROFIL",
            ["page_tournaments"] = "TURNIEJE",
            ["page_seasons"] = "SEZONY",

            ["profile_search_ph"] = "Wpisz nick gracza",
            ["profile_search_btn"] = "SZUKAJ",
            ["profile_prompt"] = "Wyszukaj gracza, aby zobaczyć statystyki",
            ["profile_ranks"] = "RANGI",
            ["profile_stats"] = "STATYSTYKI",
            ["profile_seasons"] = "OSTATNIE MECZE",
            ["profile_wins"] = "WYGRANE",
            ["profile_matches"] = "MECZE",
            ["profile_goals"] = "BRAMKI",
            ["profile_assists"] = "ASYSTY",
            ["profile_col_season"] = "DATA",
            ["profile_col_rank"] = "RANGA",
            ["profile_col_mmr"] = "MMR",
            ["profile_loading"] = "Ładowanie…",
            ["profile_error"] = "Nie udało się pobrać tego gracza. Sprawdź nick (profil Rocket League musi być publiczny).",
            ["profile_no_key"] = "Ustaw klucz API tracker.gg w Ustawieniach, aby pobierać prawdziwe profile.",

            ["tour_all"] = "WSZYSTKIE",
            ["tour_rlcs"] = "RLCS",
            ["tour_major"] = "MAJORY",
            ["tour_regional"] = "REGIONALNE",
            ["tour_empty"] = "Brak turniejów",
            ["tour_loading"] = "Ładowanie turniejów…",

            ["season_changes"] = "ZMIANY",
            ["season_new"] = "NOWOŚCI",
            ["season_rewards"] = "NAGRODY",

            ["refresh"] = "↻ ODŚWIEŻ",
            ["news_loading"] = "Ładowanie newsów…",
            ["news_empty"] = "Brak newsów",
        };
    }
}
